extends "res://tests/check_quest_gui.gd"

func run() -> void:
	var database := root.get_node("GameDatabase")
	var progress := root.get_node("CafeProgress")
	var save := root.get_node("SaveSystem")
	database.upsert_record("inventory",{"id":"product_butter_cloud_buns","quantity":50})
	var hub = load("res://scenes/cafe/cafe_hub.tscn").instantiate()
	root.add_child(hub)
	await process_frame
	hub.world.set_process(false)
	hub.world._process(0)
	hub._process(0)
	var stats: Dictionary = database.get_player_stats().duplicate(true)
	await click(hub.display_stock_buttons[0])
	check(is_instance_valid(hub.modal),"Clicking display opens management")
	await click(hub.modal.find_child("StoreDisplay",true,false))
	check(progress.product_stock(0)==0,"Store clears display stock")
	check(progress.stored_stock(0)==50,"Store keeps entire remaining batch")
	check(not hub.world.display_products[0].visible,"Stored display appears empty")
	check(progress.purchase(0).is_empty(),"Customers cannot buy stored items")
	check(not progress.move_product_stock(0,false),"Cannot store batch twice")
	save.save_now()
	save.load_save()
	database._load_player_tables()
	check(progress.stored_stock(0)==50,"Pantry stock persists on reload")
	await click(hub.get_node("PantryButton"))
	await click(hub.modal.find_child("SellStored0",true,false))
	check(progress.stored_stock(0)==0,"Sell removes stored stock")
	check(progress.product_stock(0)==50,"Sell restores display stock")
	check(hub.world.display_products[0].visible,"Restocked display is visible")
	check(not progress.move_product_stock(0,true),"Cannot sell batch twice")
	check(database.get_player_stats().coins==stats.coins,"Transfers do not create coins")
	check(database.get_player_stats().xp==stats.xp,"Transfers do not create XP")
	check(not progress.purchase(0).is_empty(),"Customers can buy restocked item")
	check(progress.product_stock(0)==49,"Sale consumes one restocked item")
	check(progress.move_product_stock(0,false),"Remaining stock can be stored again")
	check(progress.stored_stock(0)==49,"Store uses remaining quantity")
	await RenderingServer.frame_post_draw
	root.get_texture().get_image().save_png("res://../tmp/pantry_storage.png")
	print("Pantry storage: %d failures" % failures)
	quit(failures)
